#   schedtoold.conf -- Configuration file for schedtool.
#   (c) 2022 Nitrux Latinoamericana S.C.
#
#   Use schedtoold at your _OWN_ risk!
#   You must agree before using schedtoold.
#
#   How to configure?
#   -----------------
#   [%group:|user:]   program-name    schedtool parameter
#
#   Rules are parsed from top downwards. The first rule matches is valid!

ALL: /usr/bin/kwin_x11 -F -p 15 -n 4 -a 0xf
