[MAINWINDOW]
PLAYLIST_POS=-1

[PLAYLIST]
LASTPLAYLIST=@Invalid()

[Settings]
autoScan=true
fetchArtwork=true

[WINDOW]
GEOMETRY=@Variant(\0\0\0\x14@W\x80\0\0\0\0\0@T\0\0\0\0\0\0@\x88\xd0\0\0\0\0\0@\x82\x30\0\0\0\0\0)
